# Generated by Django 4.2.3 on 2023-07-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
